Repository SatelliteQE/robottelo-ci, pull requests merged in 2018-12, with the labels that each got.

#1371 Nailgun version as per Pre-Upgrade sat version
  scripts/satellite6-upgrade-run-scenarios.sh
Labels: in progress, review

#1335 Block tier jobs for pipeline that receive z-stream only
  jobs/parameters/satellite6_provisioning_parameters.yaml
  jobs/satellite6-automation.yaml
Labels: ready, review

#1376 Lock FAM checkout to non-breaking commit
  workflows/lib/runPlaybook.groovy
Labels: in progress, review

#1379 Update sat-clone command
  workflows/test/satelliteClone.groovy
Labels: review

#1368 Update for RHEL 7.6 and RHEL 6.10
  scripts/satellite6-populate-template.sh
Labels: in progress, review

#1380 Removed manifest deletion as it is not required
  scripts/satellite6-upgrade-tier-source.sh
Labels: in progress, review

#1381 disable logging to report portal
  scripts/satellite6-automation.sh
Labels: in progress, review

#1396 Use product_upgrade task to upgrade
  scripts/satellite6_upgrader.sh
Labels: bug, review

#1405 Upgrade moving to python3 in Jenkins
  jobs/builders/satellite6_upgrade_builders.yaml
  jobs/builders/satellite6_upgrade_existence_builders.yaml
  jobs/builders/satellite6_upgrade_scenarios_builders.yaml
  jobs/satellite6-automation.yaml
Labels: review

#1383 Fix nailgun version for preupgrade scenarios
  scripts/satellite6-upgrade-run-scenarios.sh
  scripts/satellite6-upgrade-trigger.sh
Labels: in progress, review
