Repository SatelliteQE/robottelo-ci, pull requests merged in 2018-03, with the labels that each got.

#1018 Define ruby version in cleanup for foreman_theme_satellite
  workflows/test/foreman-lib.groovy
  workflows/test/foreman-theme-satellite.groovy
Labels: review

#1019 pretend the release we read from the rpm spec is a float
  workflows/lib/packaging.groovy
Labels: review

#1009 Allow user to select client OS to populate archs
  jobs/satellite6-client-populate.yaml
  scripts/satellite6-client-arch-template.sh
  scripts/satellite6-configure-variables.sh
Labels: review

#1016 Added support for foreman-maintain in CustomerDb
  jobs/satellite6-db-upgrade-migrate.yaml
  scripts/satellite6_db_upgrade_migrate.sh
Labels: review

#1021 set download_logs to true for packaging with obal
  workflows/lib/packaging.groovy
Labels: review

#1022 Fix pipelines when comparing content views
  workflows/lib/releaseQAFunctions.groovy
Labels: review

#1020 Added support for CI Ruby Code Coverage
  jobs/satellite6-automation.yaml
  scripts/satellite6-code-coverage.sh
  scripts/satellite6-consolidated-coverage-report.sh
Labels: review

#1024 Update node for sat-clone tests
  jobs/unittest/sat6-unit-test-satellite-clone.yaml
Labels: review

#1023 also undefine foremandist when querying rpm specs
  workflows/lib/packaging.groovy
Labels: review

#1028 Make Ruby code Coverage run optional temporarily
  jobs/parameters/satellite6_automation_parameters.yaml
  jobs/parameters/satellite6_provisioning_parameters.yaml
  jobs/satellite6-automation.yaml
  scripts/satellite6-code-coverage.sh
Labels: review

#1029 Drop param from the provisioning_parameters yaml file
  jobs/parameters/satellite6_provisioning_parameters.yaml
Labels: review

#1027 use obal definition from foreman-infra
  jobs/rhui-3-rhui-packaging-release-build.yaml
  jobs/rhui-3-rhui-packaging-scratch-build.yaml
  jobs/rhui-3-rhui-packaging-update.yaml
  jobs/sat-63-satellite-packaging-release-build.yaml
  jobs/sat-63-satellite-packaging-scratch-build.yaml
  jobs/sat-63-satellite-packaging-update.yaml
  workflows/lib/obal.groovy
  workflows/lib/packaging.groovy
  workflows/lib/updatePackaging.groovy
Labels: review

#1030 Fix the ruby code coverage optional run
  jobs/publishers/satellite6_automation_archiver.yaml
  scripts/satellite6-code-coverage.sh
  scripts/satellite6-consolidated-coverage-report.sh
Labels: review

#1031 Update cherry pick workflow to 6.2.15
  workflows/identifyCherryPicksWorkflow.groovy
Labels: review

#1033 Fix typo in customer db Job
  scripts/satellite6_db_upgrade_migrate.sh
Labels: review

#1037 Fix missed toolBelt re-factor
  workflows/releasePackageWorkflow.groovy
Labels: review

#1038 Fix typo in toolBelt command call
  workflows/releasePackageWorkflow.groovy
Labels: review

#1040 Update release job to use the correct tool_belt command when setting …
  workflows/releasePackageWorkflow.groovy
Labels: review

#1041 Rename move to modified stage to set cherry picked
  workflows/releasePackageWorkflow.groovy
Labels: review

#1039 fix typo
  workflows/releasePackageWorkflow.groovy
Labels: review

#1042 Fix refactor typos in update packaging
  workflows/lib/updatePackaging.groovy
Labels: review

#1043 Fix setup-environment command
  workflows/lib/updatePackaging.groovy
Labels: review

#1044 Mass registration job shell script fixed
  jobs/satellite6-mass-registration.yaml
Labels: review

#1045 Fix missing quote in updatePackaging job
  workflows/lib/updatePackaging.groovy
Labels: review

#1048 Remove unused project option from git merge-request step
  workflows/lib/updatePackaging.groovy
Labels: review

#1046 Support new packages in version and release comparison
  workflows/lib/packaging.groovy
Labels: review

#1047 Added more description for mass registration job
  jobs/satellite6-mass-registration.yaml
Labels: review

#1049 Do not exit abruptly if PYTEST_OPTIONS is specified
  scripts/satellite6-standalone-automation.sh
Labels: bug, review

#1050 Pass in tool_belt_config to mark_bugs_built
  workflows/lib/packaging.groovy
Labels: review

#1052 Fix improperly scoped tool_belt commands
  workflows/lib/packaging.groovy
Labels: review

#1053 Fix typo with rpm_built
  workflows/lib/packaging.groovy
Labels: review

#1051 Only mark bugs built if success building
  workflows/lib/packaging.groovy
Labels: review

#1055 create individual kerberos credential caches per run
  workflows/lib/kerberos.groovy
  workflows/lib/packaging.groovy
Labels: review

#1054 Add KOJI as new option for SATELLITE_DISTRIBUTION
  jobs/satellite6-automation.yaml
  jobs/satellite6-installer.yaml
  scripts/installer.sh
  scripts/satellite6-automation-instances.sh
  scripts/satellite6-code-coverage.sh
  scripts/satellite6-graceful-shutdown.sh
  scripts/satellite6-provisioning.sh
Labels: review

#1056 check for the package folder, not `*.spec` when verifying the package
  workflows/lib/packaging.groovy
Labels: review

#1059 6.3 Z-Stream Upgrade support
  jobs/satellite6-automation.yaml
  jobs/satellite6-upgrader.yaml
Labels: review

#1063 make satellite-packaging jobs concurrent
  jobs/sat-63-satellite-packaging-release-build.yaml
  jobs/sat-63-satellite-packaging-scratch-build.yaml
Labels: in progress, review

#1064 only find non-deleted changed packages
  workflows/lib/packaging.groovy
Labels: in progress, review

#1060 Added more user notes for mass registration job
  jobs/satellite6-mass-registration.yaml
Labels: in progress, review

#1062 Fixes #1061 - remove of a deprecated and invalid block inside ruby coverage
  scripts/satellite6-code-coverage.sh
Labels: in progress, review

#1066 fix typo in func name
  workflows/lib/packaging.groovy
Labels: in progress, review

#1069 compare targetBranch..MR, not MR..targetBranch
  workflows/lib/packaging.groovy
Labels: in progress, review

#1071 use sync_products for sat-maint
  workflows/maintenance/releasePipeline.groovy
Labels: in progress, review

#1072 Don't check version and release for new packages
  workflows/lib/packaging.groovy
Labels: in progress, review

#1065 Added support for foreman-maintain in satellite6-upgrader
  jobs/satellite6-upgrader.yaml
  scripts/satellite6_upgrader.sh
Labels: in progress, review

#1074 try to convert release to a float, but don't fail if that's not possible
  workflows/lib/packaging.groovy
Labels: in progress, review

#1073 Added multiple platform support for mass registration job
  jobs/satellite6-mass-registration.yaml
  scripts/satellite6-mass-registration.sh
Labels: in progress, review

#1075 Use rpmdev-vercmp for version comparison logic
  workflows/lib/packaging.groovy
Labels: in progress, review

#1036 Update release package workflow to use declarative syntax
  workflows/releasePackageWorkflow.groovy
Labels: review

#1076 Include coverage run to happen for all except UPSTREAM
  scripts/satellite6-code-coverage.sh
Labels: in progress, review

#1070 Move to python3.6 interpreter and python3 branch
  jobs/builders/satellite6_automation_builders.yaml
  jobs/satellite6-automation.yaml
Labels: in progress, review

#1078 Fix groovy syntax errors
  workflows/lib/packaging.groovy
Labels: in progress, review

#1079 Fix package workflow declarative syntax
  workflows/releasePackageWorkflow.groovy
Labels: in progress, review

#1080 Add brew build check
  workflows/lib/packaging.groovy
Labels: in progress, review

#1081 Use stdout, not status
  workflows/lib/packaging.groovy
Labels: in progress, review
