Repository SatelliteQE/robottelo-ci, pull requests merged in 2018-04, with the labels that each got.

#1083 set-build-state lives under the bugzilla commands
  workflows/releasePackageWorkflow.groovy
Labels: in progress, review

#1087 keep packaging builds longer than the default
  jobs/sat-63-satellite-packaging-release-build.yaml
  jobs/sat-63-satellite-packaging-scratch-build.yaml
Labels: in progress, review

#1088 Include foreman/ui_airgun and exclude foreman/ui for 6.4
  scripts/satellite6-automation.sh
  scripts/satellite6-upgrade-tier-source.sh
Labels: in progress, review

#1092 Add support to provision RHEL7 and RHEL6 host
  jobs/satellite6-automation.yaml
  scripts/satellite6-add-provison-host.sh
  scripts/satellite6-libvirt-install.sh
  scripts/satellite6-provision-host-template.sh
Labels: in progress, review

#1093 Adjust unit-test-bastion to reflect usage in foreman-infra
  jobs/unittest/satellite6-unit-test-bastion.yaml
Labels: in progress, review

#1094 Some minor fixes to get the package install successful
  scripts/satellite6-provision-host-template.sh
Labels: in progress, review

#1096 Use the latest RHEL releases for syncing content
  scripts/satellite6-populate-template.sh
Labels: in progress, review

#1095 Sanity check jobs for capsules
  jobs/satellite6-automation.yaml
  scripts/satellite6-libvirt-capsule-install.sh
Labels: in progress, review

#1097 add sat-64-satellite-packaging-update
  jobs/sat-64-satellite-packaging-update.yaml
  workflows/releasePackageWorkflow.groovy
Labels: in progress, review

#1098 Run all the jobs on sat6-rhel7 only as sat6-rhel6 is down
  jobs/satellite6-automation.yaml
  jobs/satellite6-betelgeuse.yaml
Labels: in progress, review

#1099 some minor fixes for the sanity-check jobs
  scripts/satellite6-libvirt-capsule-install.sh
  scripts/satellite6-provision-host-template.sh
Labels: in progress, review

#1103 drop satellite6-packaging-builder-* jobs
  jobs/publishers/cleanup_vagrant.yaml
  jobs/satellite6-builder.yaml
Labels: in progress, review

#1101 Added scripts to configure capsules on satellite6
  jobs/satellite6-automation.yaml
  scripts/satellite6-configure-capsule-variables.sh
  scripts/satellite6-populate-capsule-template.sh
Labels: in progress, review

#1104 Fixes the OSP support in DB migrate job
  jobs/satellite6-db-upgrade-migrate.yaml
  scripts/satellite6_db_upgrade_migrate.sh
Labels: review

#1102 use upstream jenkins-job-builder master again
  jobs/publishers/destroy_keytab.yaml
  jobs/satellite6-slave-builder.yaml
  requirements.txt
Labels: in progress, review

#1106 Few fixes for automation tier jobs
  jobs/builders/satellite6_automation_builders.yaml
Labels: in progress, review

#1107 Some minor tweaks to capsule sanity-check jobs
  jobs/satellite6-automation.yaml
  scripts/satellite6-configure-capsule-variables.sh
  scripts/satellite6-libvirt-capsule-install.sh
Labels: in progress, review

#1108 Added support to configure external capsule
  scripts/satellite6-libvirt-capsule-install.sh
  scripts/satellite6-provision-host-template.sh
Labels: in progress, review

#1114 Add upstream-nightly in python3 conditional step
  jobs/builders/satellite6_automation_builders.yaml
  jobs/builders/satellite6_provisioning_builders.yaml
Labels: in progress, review

#1110 Add check for foreman-maintain in upgrade pipeline
  jobs/satellite6-automation.yaml
Labels: in progress, review

#1116 Don't store ssh hostkeys (as remote host identification changes every automation run)
  scripts/satellite6-automation-instances.sh
  scripts/satellite6-code-coverage.sh
Labels: review

#1119 Add interface for capsule sanity job
  jobs/satellite6-automation.yaml
  scripts/satellite6-libvirt-capsule-install.sh
Labels: in progress, review

#1122 Fixes the upgrade tier job macros
  jobs/builders/satellite6_upgrade_tiers_builders.yaml
Labels: bug, review

#1121 Split tiers into multiple instances also for upstream
  scripts/satellite6-automation-instances.sh
  scripts/satellite6-graceful-shutdown.sh
Labels: in progress, review

#1123 Assign capsule subnet a unique name.
  scripts/satellite6-configure-capsule-variables.sh
  scripts/satellite6-libvirt-install.sh
Labels: in progress, review

#1124 Sets the satellite_hostname environ variable.
  scripts/satellite6_db_upgrade_migrate.sh
Labels: in progress, review

#1125 Pass numeric values rather than string values for hostgroup creation
  scripts/satellite6-populate-capsule-template.sh
Labels: in progress, review

#1126 only archive olde versions if there actually is one
  workflows/releaseQAWorkflow.groovy
Labels: in progress, review

#1128 Added support for 6.4 to all the jobs
  jobs/satellite6-handle-tier-instances.yaml
  jobs/satellite6-installer.yaml
  jobs/satellite6-libvirt-install.yaml
  jobs/satellite6-populate.yaml
  jobs/satellite6-standalone-automation.yaml
Labels: in progress, review

#1100 make the branch map more generic and use it for ruby versions
  jobs/release/projects/release-test-repo.yaml
  jobs/release/projects/rhui-release-pulp-docker.yaml
  jobs/release/projects/rhui-release-pulp-ostree.yaml
  jobs/release/projects/rhui-release-pulp-rpm.yaml
  jobs/release/projects/rhui-release-pulp.yaml
  jobs/release/projects/sat-release-bastion.yaml
  jobs/release/projects/sat-release-dynflow.yaml
  jobs/release/projects/sat-release-foreman-bootdisk.yaml
  jobs/release/projects/sat-release-foreman-discovery.yaml
  jobs/release/projects/sat-release-foreman-docker.yaml
  jobs/release/projects/sat-release-foreman-installer.yaml
  jobs/release/projects/sat-release-foreman-openscap.yaml
  jobs/release/projects/sat-release-foreman-remote-execution.yaml
  jobs/release/projects/sat-release-foreman-selinux.yaml
  jobs/release/projects/sat-release-foreman-tasks.yaml
  jobs/release/projects/sat-release-foreman-theme-satellite.yaml
  jobs/release/projects/sat-release-foreman-virt-who-configure.yaml
  jobs/release/projects/sat-release-foreman.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman-admin.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman-bootdisk.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman-discovery.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman-docker.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman-remote-execution.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman-tasks.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman-virt-who-configure.yaml
  jobs/release/projects/sat-release-hammer-cli-foreman.yaml
  jobs/release/projects/sat-release-hammer-cli-katello.yaml
  jobs/release/projects/sat-release-hammer-cli.yaml
  jobs/release/projects/sat-release-katello-installer.yaml
  jobs/release/projects/sat-release-katello.yaml
  jobs/release/projects/sat-release-pulp-docker.yaml
  jobs/release/projects/sat-release-pulp-ostree.yaml
  jobs/release/projects/sat-release-pulp-puppet.yaml
  jobs/release/projects/sat-release-pulp-rpm.yaml
  jobs/release/projects/sat-release-pulp.yaml
  jobs/release/projects/sat-release-runcible.yaml
  jobs/release/projects/sat-release-satellite-installer.yaml
  jobs/release/projects/sat-release-smart-proxy-dhcp-remote-isc.yml
  jobs/release/projects/sat-release-smart-proxy-dynflow.yaml
  jobs/release/projects/sat-release-smart-proxy-openscap.yaml
  jobs/release/projects/sat-release-smart-proxy-remote-execution-ssh.yaml
  jobs/release/projects/sat-release-smart-proxy.yaml
  jobs/unittest/sat6-unit-test-foreman-theme-satellite.yaml
  workflows/lib/branch_map.groovy
  workflows/releasePackageWorkflow.groovy
  workflows/test/foreman-theme-satellite.groovy
Labels: in progress, review

#1129 The latest version of pylarion requires .pylarion
  scripts/satellite6-install-pylarion.sh
Labels: in progress, review

#1113 Upload Upgrade Tier Test Results to polarion
  jobs/satellite6-automation.yaml
  jobs/satellite6-betelgeuse.yaml
Labels: in progress, review

#1117 Source new config for temporary installation fixes
  jobs/parameters/satellite6_provisioning_parameters.yaml
  jobs/satellite6-installer.yaml
  scripts/installer.sh
  scripts/satellite6-provisioning.sh
Labels: review

#1131 add ansible release pipe
  jobs/release/ansible-release-pipeline.yaml
  workflows/ansiblePipeline.groovy
Labels: in progress, review

#1133 Use pytest-env plugin and set PYTHONHASHSEED for ui_airgun
  scripts/satellite6-automation.sh
  scripts/satellite6-standalone-automation.sh
  scripts/satellite6-upgrade-tier-source.sh
Labels: in progress, review

#1130 Add 6.4 version to upgrader job
  jobs/satellite6-upgrader.yaml
Labels: in progress, review

#1138 Fix: Upgrade Tier results upload to polarion Fixes #1137
  scripts/satellite6-betelgeuse-test-run.sh
Labels: review

#1140 Fix : POLARION RELEASE in Upgrade Tier Tests result upload
  jobs/satellite6-automation.yaml
  scripts/satellite6-betelgeuse-test-run.sh
Labels: review
