Repository SatelliteQE/robottelo-ci, pull requests merged in 2018-09, with the labels that each got.

#1248 Added support to populate n-1 clients repo
  jobs/satellite6-client-populate.yaml
  scripts/satellite6-configure.sh
Labels: in progress, review

#1273 added -o junit_suite_name to the py.tet arguments
  scripts/satellite6-automation.sh
  scripts/satellite6-standalone-automation.sh
  scripts/satellite6-upgrade-existence.sh
  scripts/satellite6-upgrade-run-scenarios.sh
  scripts/satellite6-upgrade-tier-source.sh
  scripts/satellite6_db_upgrade_migrate.sh
  scripts/satellite6_upgrader.sh
Labels: Infrastructure, enhancement, in progress, review

#1276 Fixes triggering new jobs
  jobs/foreman-maintain-automation.yaml
  jobs/satellite6-automation.yaml
  jobs/satellite6-db-upgrade-migrate.yaml
  scripts/satellite6-libvirt-capsule-install.sh
  scripts/satellite6_db_upgrade_migrate.sh
Labels: in progress, review

#1280 fix release-qa for sat-maint(-next)
  workflows/maintenance-next/releasePipelineAttributes.groovy
  workflows/maintenance/releasePipelineAttributes.groovy
  workflows/maintenance/releaseQAWorkflow.groovy
Labels: in progress, review

#1277 Removes sleep and replaces with a method to check ssh availability
  scripts/satellite6-automation-instances.sh
Labels: in progress, review

#1279 Update email report generation template
  jobs/foreman-maintain-automation.yaml
  jobs/satellite6-automation.yaml
  lib/python/satellite6-automation-report.py
  lib/python/templates/email_report.html
  scripts/foreman-maintain-automation.sh
  scripts/satellite6-automation-report.sh
Labels: in progress, review

#1283 implemented the rp_logger configuration
  scripts/satellite6-automation.sh
Labels: review

#1284 Satellite6 instances scripts needs fabric installed before execution
  scripts/satellite6-automation-instances.sh
Labels: in progress, review

#1288 Removes all the insane logic
  scripts/satellite6-automation-instances.sh
Labels: in progress, review

#1290 Get the insane logic back in
  scripts/satellite6-automation-instances.sh
Labels: in progress, review

#1293 Wait for hammer ping to be Ok
  scripts/satellite6-automation-instances.sh
Labels: in progress, review

#1281 add a releaser for foreman_hooks
  jobs/release/projects/repos/foreman_hooks_repo.groovy
  jobs/release/projects/sat-release-foreman-hooks.yaml
Labels: in progress, review

#1285 test dynflow with a pipeline
  jobs/builders/test_dynflow.yaml
  jobs/unittest/repos/dynflow.groovy
  jobs/unittest/sat6-unit-test-dynflow.yaml
  jobs/unittest/satellite6-unit-test-dynflow.yaml
  scripts/test_dynflow.sh
  workflows/test/dynflow.groovy
Labels: in progress, review

#1297 fixed quotes at RP_LAUNCH_TAGS
  scripts/satellite6-automation.sh
Labels: in progress, review

#1286 test foreman-tasks with a pipeline
  jobs/scm/foreman_tasks_gitlab.yaml
  jobs/unittest/repos/foreman_tasks.groovy
  jobs/unittest/sat6-unit-test-foreman-tasks.yaml
  jobs/unittest/satellite6-unit-test-foreman-tasks.yaml
  workflows/test/foreman-lib.groovy
  workflows/test/foreman-plugin.groovy
Labels: in progress, review

#1299 Update foreman-discovery unit test job
  jobs/unittest/repos/foreman_discovery.groovy
  jobs/unittest/sat6-unit-test-foreman-discovery.yaml
  jobs/unittest/satellite6-unit-test-foreman-discovery.yaml
Labels: in progress, review

#1300 Switch hammer_cli_foreman to the new job format
  jobs/unittest/repos/hammer_cli_foreman.groovy
  jobs/unittest/sat6-unit-test-hammer-cli-foreman.yaml
  jobs/unittest/satellite6-unit-test-hammer-cli-foreman.yaml
Labels: in progress, review

#1301 Make all unit test jobs concurrent
  jobs/unittest/sat6-unit-test-dynflow.yaml
  jobs/unittest/sat6-unit-test-foreman-bootdisk.yaml
  jobs/unittest/sat6-unit-test-foreman-discovery.yaml
  jobs/unittest/sat6-unit-test-foreman-docker.yaml
  jobs/unittest/sat6-unit-test-foreman-installer.yaml
  jobs/unittest/sat6-unit-test-foreman-openscap.yaml
  jobs/unittest/sat6-unit-test-foreman-remote-execution.yaml
  jobs/unittest/sat6-unit-test-foreman-tasks.yaml
  jobs/unittest/sat6-unit-test-foreman-theme-satellite.yaml
  jobs/unittest/sat6-unit-test-foreman-virt-who-configure.yaml
  jobs/unittest/sat6-unit-test-foreman.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman-remote-execution.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman-tasks.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman-virt-who-configure.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-katello.yaml
  jobs/unittest/sat6-unit-test-katello-installer.yaml
  jobs/unittest/sat6-unit-test-katello.yaml
  jobs/unittest/sat6-unit-test-ohsnap.yaml
  jobs/unittest/sat6-unit-test-puppet-candlepin.yaml
  jobs/unittest/sat6-unit-test-puppet-capsule.yaml
  jobs/unittest/sat6-unit-test-puppet-certs.yaml
  jobs/unittest/sat6-unit-test-puppet-foreman-proxy-content.yaml
  jobs/unittest/sat6-unit-test-puppet-foreman-proxy.yaml
  jobs/unittest/sat6-unit-test-puppet-foreman.yaml
  jobs/unittest/sat6-unit-test-puppet-katello.yaml
  jobs/unittest/sat6-unit-test-puppet-pulp.yaml
  jobs/unittest/sat6-unit-test-puppet-puppet.yaml
  jobs/unittest/sat6-unit-test-runcible.yaml
  jobs/unittest/sat6-unit-test-satellite-installer.yaml
  jobs/unittest/sat6-unit-test-smart-proxy-dhcp-remote-isc.yaml
  jobs/unittest/sat6-unit-test-smart-proxy-dynflow.yaml
  jobs/unittest/sat6-unit-test-smart-proxy.yaml
  jobs/unittest/satellite6-unit-test-hammer-cli-foreman-discovery.yaml
  jobs/unittest/satellite6-unit-test-hammer-cli.yaml
  jobs/unittest/satellite6-unit-test-kafo.yaml
  jobs/unittest/satellite6-unit-test-smart-proxy-openscap.yaml
  jobs/unittest/satellite6-unit-test-smart-proxy-remote-execution-ssh.yaml
  jobs/unittest/satellite6-unit-test-snapper.yaml
  jobs/unittest/satellite6-unit-test-test-repo.yaml
  jobs/unittest/satellite6-unit-test-tool-belt.yaml
Labels: in progress, review

#1304 speed up setup_foreman()
  workflows/test/foreman-lib.groovy
Labels: in progress, review

#1305 ignore npm install failure instead of using --ignore-scripts
  workflows/test/foreman-lib.groovy
Labels: in progress, review

#1308 explicitly call setup_obal
  workflows/lib/packaging.groovy
  workflows/lib/updatePackaging.groovy
Labels: in progress, review
