Repository SatelliteQE/robottelo-ci, pull requests merged in 2018-11, with the labels that each got.

#1353 Remove the Add Packages To Compose step
  workflows/releaseSatellitePipeline.groovy
Labels: in progress, review

#1354 move satellite-packaging jobs to an unified template
  jobs/sat-63-satellite-packaging-release-build.yaml
  jobs/sat-63-satellite-packaging-scratch-build.yaml
  jobs/sat-63-satellite-packaging-update.yaml
  jobs/sat-64-satellite-packaging-update.yaml
  jobs/sat-65-satellite-packaging-update.yaml
  jobs/satellite-packaging.yaml
Labels: in progress, review

#1355 Convert tool_belt MR tests to pipeline
  jobs/builders/test_tool_belt.yaml
  jobs/scm/tool_belt_gitlab.yaml
  jobs/unittest/sat6-unit-test-tool-belt.yaml
  jobs/unittest/satellite6-unit-test-tool-belt.yaml
  workflows/test/tool_belt.groovy
Labels: in progress, review

#1358 Fix multiple subscriptions id in populate job
  scripts/satellite6-populate-template.sh
Labels: in progress, review

#1361 RP reogranization - using a single Satellite6 project
  scripts/satellite6-automation.sh
Labels: in progress, review

#1360 New job: satellite6-baseimage-deploy
  jobs/satellite6-baseimage-deploy.yaml
  scripts/satellite6-baseimage-deploy.sh
Labels: enhancement, in progress, review

#1363 Remove hard coded ruby version in favor of branch map version
  workflows/releasePackageWorkflow.groovy
Labels: in progress, review

#1362 satellite6-baseimage-deploy: Put param in quotes
  scripts/satellite6-baseimage-deploy.sh
Labels: in progress, review

#1364 Fix katello unit test database issues
  workflows/test/foreman-lib.groovy
  workflows/test/katello.groovy
Labels: in progress, review

#1365 satellite6-baseimage-deploy: Parametrize more
  jobs/satellite6-baseimage-deploy.yaml
  scripts/satellite6-baseimage-deploy.sh
Labels: review

#1366 fix replacing the gem during foreman tests
  workflows/test/foreman-lib.groovy
Labels: in progress, review

#1350 Added job for custom certs satellite install/upgrade
  jobs/custom-certs-automation.yaml
  scripts/custom_certs.sh
Labels: in progress, review

#1369 Update satellite6-automation.sh
  scripts/satellite6-automation.sh
Labels: in progress, review

#1372 better explanation for custom source image in provisioning job
  jobs/satellite6-automation.yaml
Labels: in progress, review

#1311 Added airgun to upload tests from airgun folder
  jobs/satellite6-automation.yaml
  jobs/satellite6-betelgeuse.yaml
  scripts/satellite6-betelgeuse-test-case.sh
Labels: ready, review
