Repository SatelliteQE/robottelo-ci, pull requests merged in 2018-08, with the labels that each got.

#1242 Added support for using satellite-clone rpm
  jobs/satellite6-db-upgrade-migrate.yaml
  scripts/satellite6_db_upgrade_migrate.sh
Labels: enhancement, in progress, review

#1246 Clean up tool_belt usage and reduce git operations
  workflows/identifyCherryPicksWorkflow.groovy
  workflows/lib/packaging.groovy
  workflows/lib/releaseQAFunctions.groovy
  workflows/lib/toolbelt.groovy
  workflows/lib/updatePackaging.groovy
  workflows/releasePackageWorkflow.groovy
  workflows/releaseSatellitePipeline.groovy
Labels: in progress, review

#1252 Fix error in checkout script for tool_belt
  workflows/lib/toolbelt.groovy
Labels: in progress, review

#1254 Checkout tool_belt to tool_belt directory
  workflows/lib/toolbelt.groovy
Labels: in progress, review

#1255 Set archive directory to tool_belt
  workflows/lib/updatePackaging.groovy
  workflows/releasePackageWorkflow.groovy
Labels: in progress, review

#1256 Adjust releaseQA for new toolBelt command
  workflows/lib/releaseQAFunctions.groovy
Labels: in progress, review

#1247 Remove set external tracker step from package release
  workflows/releasePackageWorkflow.groovy
Labels: in progress, review

#1250 Update katello-unit tests to a scripted pipeline
  jobs/unittest/sat6-unit-test-katello.yaml
  jobs/unittest/satellite6-unit-test-katello.yaml
  scripts/add_bastion_gitlab.sh
  scripts/add_foreman_docker_gitlab.sh
  workflows/test/katello.groovy
Labels: in progress, review

#1259 install plugin with development dependencies
  workflows/test/foreman-lib.groovy
Labels: in progress, review

#1260 split db actions
  workflows/test/katello.groovy
Labels: in progress, review

#1249 Run tests on customer db
  jobs/satellite6-db-upgrade-migrate.yaml
  scripts/satellite6_db_upgrade_migrate.sh
Labels: in progress, review

#1245 create copied activation keys, pointing to the archived environment
  ansible/playbooks/copy_activation_key.yml
  workflows/6.3/releasePipelineAttributes.groovy
  workflows/6.4/releasePipelineAttributes.groovy
  workflows/lib/releaseQAFunctions.groovy
  workflows/releaseQAWorkflow.groovy
Labels: in progress, review

#1262 link brew subtasks, as that is what we really care about
  workflows/lib/packaging.groovy
Labels: in progress, review

#1267 fix detection of brew tasks
  workflows/lib/packaging.groovy
Labels: in progress, review

#1265 disable AK copy until we have 6.3.3 on dogfood
  workflows/releaseQAWorkflow.groovy
Labels: in progress, review

#1263 Don't run UI smoke tests for upgrades for 6.4
  scripts/satellite6-upgrade-tier-source.sh
Labels: review

#1271 unify the two maintenance qa workflows
  jobs/release/sat-maintenance-next-release-qa.yaml
  jobs/release/sat-maintenance-release-qa.yaml
  workflows/maintenance-next/releasePipelineAttributes.groovy
  workflows/maintenance-next/releaseQAWorkflow.groovy
  workflows/maintenance/releasePipelineAttributes.groovy
  workflows/maintenance/releaseQAWorkflow.groovy
Labels: in progress, review

#1270 Fixes the existence tests job, by injecting req. parameters
  jobs/satellite6-automation.yaml
Labels: in progress, review

#1269 trigger foreman-maintain automation after sanity jobs
  jobs/foreman-maintain-automation.yaml
  jobs/satellite6-automation.yaml
  jobs/satellite6-client-populate.yaml
  jobs/satellite6-discovery-remaster.yaml
  jobs/satellite6-rcm-compose.yaml
  scripts/foreman-maintain-automation.sh
Labels: in progress, review

#1274 [sat6-populate]Add location to organization
  scripts/satellite6-populate-template.sh
Labels: in progress, review

#1275 Update rhui packaging jobs with latest changes in satellite's
  jobs/rhui-3-rhui-packaging-release-build.yaml
  jobs/rhui-3-rhui-packaging-scratch-build.yaml
Labels: in progress, review
