Repository SatelliteQE/robottelo-ci, pull requests merged in 2018-10, with the labels that each got.

#1307 use rvm.groovy from foreman-infra
  jobs/release/projects/sat-release-foreman-installer.yaml
  jobs/release/projects/sat-release-katello-installer.yaml
  jobs/release/projects/sat-release-runcible.yaml
  jobs/unittest/sat6-unit-test-dynflow.yaml
  jobs/unittest/sat6-unit-test-foreman-bootdisk.yaml
  jobs/unittest/sat6-unit-test-foreman-discovery.yaml
  jobs/unittest/sat6-unit-test-foreman-docker.yaml
  jobs/unittest/sat6-unit-test-foreman-installer.yaml
  jobs/unittest/sat6-unit-test-foreman-openscap.yaml
  jobs/unittest/sat6-unit-test-foreman-remote-execution.yaml
  jobs/unittest/sat6-unit-test-foreman-tasks.yaml
  jobs/unittest/sat6-unit-test-foreman-theme-satellite.yaml
  jobs/unittest/sat6-unit-test-foreman-virt-who-configure.yaml
  jobs/unittest/sat6-unit-test-foreman.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman-remote-execution.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman-tasks.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman-virt-who-configure.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-foreman.yaml
  jobs/unittest/sat6-unit-test-hammer-cli-katello.yaml
  jobs/unittest/sat6-unit-test-katello-installer.yaml
  jobs/unittest/sat6-unit-test-katello.yaml
  jobs/unittest/sat6-unit-test-ohsnap.yaml
  jobs/unittest/sat6-unit-test-puppet-candlepin.yaml
  jobs/unittest/sat6-unit-test-puppet-capsule.yaml
  jobs/unittest/sat6-unit-test-puppet-certs.yaml
  jobs/unittest/sat6-unit-test-puppet-foreman-proxy-content.yaml
  jobs/unittest/sat6-unit-test-puppet-foreman-proxy.yaml
  jobs/unittest/sat6-unit-test-puppet-foreman.yaml
  jobs/unittest/sat6-unit-test-puppet-katello.yaml
  jobs/unittest/sat6-unit-test-puppet-pulp.yaml
  jobs/unittest/sat6-unit-test-puppet-puppet.yaml
  jobs/unittest/sat6-unit-test-runcible.yaml
  jobs/unittest/sat6-unit-test-satellite-installer.yaml
  jobs/unittest/sat6-unit-test-smart-proxy-dhcp-remote-isc.yaml
  jobs/unittest/sat6-unit-test-smart-proxy-dynflow.yaml
  jobs/unittest/sat6-unit-test-smart-proxy.yaml
  workflows/lib/rvm.groovy
  workflows/releasePackageWorkflow.groovy
  workflows/test/dynflow.groovy
  workflows/test/foreman-lib.groovy
  workflows/test/foremanInstaller.groovy
  workflows/test/hammer-cli.groovy
  workflows/test/katelloInstaller.groovy
  workflows/test/ohsnap.groovy
  workflows/test/puppet.groovy
  workflows/test/runcible.groovy
  workflows/test/satelliteInstaller.groovy
  workflows/test/smart-proxy-plugin.groovy
  workflows/test/smart-proxy.groovy
Labels: in progress, review

#1309 Add basic Satellite 6.5 jobs
  jobs/release/sat-62-release-pipeline.yaml
  jobs/release/sat-65-release-pipeline.yaml
  jobs/release/sat-65-release-qa.yaml
  jobs/sat-65-satellite-packaging-update.yaml
  workflows/6.5/releasePipelineAttributes.groovy
  workflows/lib/branch_map.groovy
  workflows/test/puppet-matrix.groovy
Labels: in progress, review

#1313 archive the current state when releasing to QA
  jobs/release/sat-63-release-qa.yaml
  jobs/release/sat-64-release-qa.yaml
  jobs/release/sat-65-release-qa.yaml
  jobs/release/sat-maintenance-next-release-qa.yaml
  jobs/release/sat-maintenance-release-qa.yaml
  workflows/releaseQAWorkflow.groovy
Labels: in progress, review

#1315 Install optional requirements for satellite6-upgrade
  scripts/satellite6-upgrade-existence.sh
  scripts/satellite6-upgrade-run-scenarios.sh
  scripts/satellite6-upgrade-tier-source.sh
  scripts/satellite6_db_upgrade_migrate.sh
  scripts/satellite6_upgrader.sh
Labels: review

#1312 Upgrade to 6.4 z-stream
  jobs/satellite6-upgrader.yaml
Labels: in progress, review

#1321 always use the same db for all actions
  workflows/test/foreman-lib.groovy
Labels: in progress, review

#1316 enable archiving for sat-maint(-next)
  workflows/maintenance/releaseQAWorkflow.groovy
Labels: in progress, review

#1317 make toolbelt archive the output if needed
  workflows/identifyCherryPicksWorkflow.groovy
  workflows/lib/releaseQAFunctions.groovy
  workflows/lib/toolbelt.groovy
  workflows/releasePackageWorkflow.groovy
Labels: in progress, review

#1306 Add support for VMware Compute Resource prov.
  scripts/satellite6-configure-variables.sh
  scripts/satellite6-populate-template.sh
  scripts/satellite6-provision-host-template.sh
Labels: Infrastructure, enhancement, review

#1322 Add kickstart repo to hostgroup
  scripts/satellite6-populate-template.sh
Labels: in progress, review

#1324 enable testing of sat-maint composes
  workflows/maintenance/releasePipeline.groovy
Labels: in progress, review

#1319 make sat-6*-release-qa jobs generate the snap number themself
  jobs/release/sat-63-release-qa.yaml
  jobs/release/sat-64-release-qa.yaml
  jobs/release/sat-65-release-qa.yaml
  jobs/release/sat-maintenance-next-release-qa.yaml
  jobs/release/sat-maintenance-release-qa.yaml
  workflows/lib/releaseQAFunctions.groovy
  workflows/maintenance/releaseQAWorkflow.groovy
  workflows/releaseQAWorkflow.groovy
Labels: in progress, review

#1325 move runOnLibvirtHost to a library file
  jobs/release/sat-62-release-pipeline.yaml
  jobs/release/sat-63-release-pipeline.yaml
  jobs/release/sat-64-release-pipeline.yaml
  jobs/release/sat-65-release-pipeline.yaml
  jobs/release/sat-maintenance-next-release-pipeline.yaml
  jobs/release/sat-maintenance-release-pipeline.yaml
  jobs/release/sat-nightly-release-pipeline.yaml
  workflows/6.2/releaseSatellitePipeline.groovy
  workflows/lib/libvirt.groovy
  workflows/nightly/releaseSatellitePipeline.groovy
  workflows/releaseSatellitePipeline.groovy
Labels: in progress, review

#1326 move forklift testing to an own function
  workflows/6.2/releaseSatellitePipeline.groovy
  workflows/lib/libvirt.groovy
  workflows/maintenance/releasePipeline.groovy
  workflows/nightly/releaseSatellitePipeline.groovy
  workflows/releaseSatellitePipeline.groovy
Labels: in progress, review

#1328 fix typo in forklift_test
  workflows/lib/libvirt.groovy
Labels: in progress, review

#1329 Fix git merge strategy issue after upgrade
  workflows/lib/gitlab.groovy
Labels: in progress, review

#1320 Create new 6.5 trigger and Pipeline with necessary changes
  jobs/builders/satellite6_automation_builders.yaml
  jobs/builders/satellite6_automation_reports_builders.yaml
  jobs/builders/satellite6_consolidated_reports_builders.yaml
  jobs/builders/satellite6_polarion_testcase_run_builders.yaml
  jobs/builders/satellite6_polarion_testrun_builders.yaml
  jobs/builders/satellite6_provisioning_builders.yaml
  jobs/builders/satellite6_standalone_automation_builders.yaml
  jobs/builders/satellite6_upgrade_tiers_builders.yaml
  jobs/satellite6-automation.yaml
  scripts/satellite6-automation.sh
Labels: in progress, review

#1331 Added a job to toggle the QE pipeline between test and production
  jobs/satellite6-qe-environment-toggle.yaml
  scripts/sat6-qe-env-toggle.sh
Labels: in progress, review

#1332 Fix issue with packaging job after jenkins upgrade
  workflows/lib/packaging.groovy
Labels: in progress, review

#1334 Added 6.5 support for standalone jobs
  jobs/capsule-installer.yaml
  jobs/parameters/satellite6_upgrade_parameters.yaml
  jobs/satellite6-client-populate.yaml
  jobs/satellite6-discovery-remaster.yaml
  jobs/satellite6-handle-tier-instances.yaml
  jobs/satellite6-installer.yaml
  jobs/satellite6-libvirt-install.yaml
  jobs/satellite6-populate.yaml
  jobs/satellite6-rcm-compose.yaml
  jobs/satellite6-standalone-automation.yaml
  jobs/satellite6-upgrader.yaml
  scripts/satellite6-populate-capsule-template.sh
  scripts/satellite6-populate-template.sh
Labels: in progress, review

#1337 Obal variables changed to drop downstream_
  workflows/lib/updatePackaging.groovy
Labels: in progress, review

#1338 Obal commits and branches during update for us
  workflows/lib/updatePackaging.groovy
Labels: in progress, review

#1336 enable AK copy for snaps again
  workflows/releaseQAWorkflow.groovy
Labels: in progress, review

#1272 start automatic release workflow
  workflows/lib/releaseQAFunctions.groovy
  workflows/maintenance-next/releasePipelineAttributes.groovy
  workflows/maintenance/releasePipelineAttributes.groovy
  workflows/maintenance/releaseQAWorkflow.groovy
  workflows/releaseSatellitePipeline.groovy
Labels: in progress, review

#1342 migrate theme-satellite to a new-style pipeline
  workflows/test/foreman-theme-satellite.groovy
Labels: in progress, review

#1343 Add step to 6.5 pipeline to add modulemd and libsolv for now
  workflows/releaseSatellitePipeline.groovy
Labels: in progress, review

#1339 Fixes populate job
  jobs/satellite6-client-populate.yaml
  scripts/satellite6-configure.sh
  scripts/satellite6-populate-template.sh
Labels: in progress, review

#1344 skip extra_files phase during compose generation
  ansible/playbooks/build_compose.yml
Labels: in progress, review

#1302 run all tests for katello, not only ruby
  workflows/test/katello.groovy
Labels: in progress, review

#1346 Skip scap policy creation
  scripts/satellite6-populate-template.sh
Labels: in progress, review
