Repository SatelliteQE/robottelo-ci, pull requests merged in 2019-11, with the labels that each got.

#1647 replace applicable usages of BZ credentials with BUGZILLA_KEY
  scripts/satellite6-automation.sh
  scripts/satellite6-standalone-automation.sh
  scripts/satellite6-upgrade-run-scenarios.sh
  scripts/satellite6-upgrade-tier-source.sh
  workflows/qe/nailgun-reviewer.groovy
Labels: review

#1646 Fixes #1645 - Add support for Testfm issue #97
  workflows/qe/satellite6-foreman-maintain-automation.groovy
Labels: review

#1649 Fix load config nitpick
  workflows/qe/satellite6-manifest-downloader.groovy
Labels: bug

#1643 Added job for testing testfm PRs
  jobs/testfm_reviewer.yaml
  workflows/qe/testfm-reviewer.groovy
Labels: review

#1635 Converted automation report job to pipeline
  jobs/satellite6-automation/satellite6-reporting.yaml
  vars/defaults.groovy
  workflows/qe/satellite6-reporting-automation.groovy
Labels: CI/CP, review

#1629 Customer DB upgrade job porting into pipeline project
  jobs/satellite6-db-upgrade-migrate.yaml
  lib/python/templates/upgrade_report.html
  vars/defaults.groovy
  workflows/qe/satellite6-db-upgrade-migrate.groovy
Labels: CI/CP, review

#1564 Refactored and restructure tier jobs
  jobs/builders/satellite6_automation_builders.yaml
  jobs/builders/satellite6_pull_artifacts_builders.yaml
  jobs/satellite6-automation/satellite6-projects.yaml
  jobs/satellite6-automation/satellite6-tiers.yaml
  workflows/qe/satellite6-automation/satellite6-tiers.groovy
Labels: CI/CP, review

#1636 Added group-id for test runs
  lib/python/satellite6-polarion-test-case-inject.py
  scripts/satellite6-betelgeuse-test-case.sh
  scripts/satellite6-betelgeuse-test-run.sh
Labels: enhancement, review

#1659 Some Fixes for 6.7
  jobs/foreman-maintain-automation.yaml
  jobs/parameters/satellite6_upgrade_parameters.yaml
  scripts/custom_certs.sh
  scripts/satellite6-client-arch-template.sh
  scripts/satellite6-populate-capsule-template.sh
  scripts/satellite6-populate-template.sh
Labels: review

#1670 backup hammer config before automation run and restore it after
  workflows/qe/satellite6-automation/satellite6-tiers.groovy
Labels: review

#1684 Fix label for builds and artifacts
  workflows/qe/satellite6-automation/satellite6-tiers.groovy
Labels: review

#1691 Fix base url for sanity
  workflows/qe/satellite6-automation/satellite6-trigger.groovy
Labels: review

#1692 Fix product name changed
  scripts/satellite6-populate-template.sh
Labels: review
