Repository SatelliteQE/robottelo-ci, pull requests merged in 2019-01, with the labels that each got.

#1408 Fixes the Polarion upgrade test case Job
  scripts/satellite6-betelgeuse-test-case.sh
Labels: review

#1410 Added timeout for workers, to prevent them from waiting indefinitely
  scripts/satellite6-automation.sh
Labels: DO NOT MERGE

#1413 Added job to trigger email using testblame
  jobs/satellite6-automation.yaml
  jobs/testblame_report.yaml
  scripts/testblame_report.sh
Labels: review

#1411 removed fab task and used delete command instead
  scripts/satellite6-upgrade-run-scenarios.sh
Labels: review

#1409 Use python3 for upgrade jobs
  jobs/satellite6-db-upgrade-migrate.yaml
  jobs/satellite6-upgrader.yaml
Labels: review

#1421 Moved jobs to python36
  jobs/satellite6-rcm-compose.yaml
  jobs/satellite6-upgrade-cleanup.yaml
Labels: review

#1424 setup fake-manifest with setupPrerequisites
  scripts/satellite6-upgrade-run-scenarios.sh
Labels: Infrastructure, enhancement, review
