Repository SatelliteQE/robottelo-ci, pull requests merged in 2019-10, with the labels that each got.

#1602 Add component-owners-mapping YAML generating job and pipeline
  jobs/satellite6-component-owners.yaml
  vars/defaults.groovy
  workflows/qe/satellite6-component-owners.groovy
Labels: enhancement

#1623 Fix groovy script approvals - use sandbox
  jobs/api-cli-reports.yaml
  jobs/satellite6-component-owners.yaml
  jobs/satellite6-manifest-downloader.yaml
  jobs/satellite6-report-portal.yaml
  jobs/satellite6-subscriptions-delete.yaml
  jobs/satellite6-upgrade-cleanup.yaml
Labels: review

#1617 Added primary and secondary owners to polarion
  jobs/satellite6-betelgeuse.yaml
  lib/python/satellite6-polarion-test-case-inject.py
  scripts/satellite6-betelgeuse-test-case.sh
Labels: enhancement, pending_testing

#1559 Added nailgun reviewer job
  jobs/nailgun_reviewer.yaml
  vars/defaults.groovy
  workflows/qe/nailgun-reviewer.groovy
Labels: review

#1625 Fixes duplicate robottelo string and nailgun job
  vars/defaults.groovy
  workflows/qe/nailgun-reviewer.groovy
Labels: review

#1632 Do not trigger custom certs job for nightly
  jobs/satellite6-automation/satellite6-provisioning.yaml
Labels: review

#1626 Converted upgrade report job to pipeline
  jobs/satellite6-automation/satellite6-reporting.yaml
  jobs/satellite6-automation/satellite6-upgrade.yaml
  vars/send_report_email.groovy
  workflows/qe/nailgun-reviewer.groovy
  workflows/qe/satellite6-reporting-upgrade.groovy
Labels: CI/CP, review

#1598 Foreman Maintain Job Ported to Pipeline
  jobs/foreman-maintain-automation.yaml
  scripts/foreman-maintain-automation.sh
  workflows/qe/satellite6-foreman-maintain-automation.groovy
Labels: CI/CP, review
