Repository SatelliteQE/robottelo-ci, pull requests merged in 2019-05, with the labels that each got.

#1496 Add global mask wrapper for subscriptions secrets
  jobs/custom-certs-automation.yaml
  jobs/satellite5-installer.yaml
  jobs/satellite6-automation.yaml
  jobs/satellite6-client-populate.yaml
  jobs/satellite6-installer.yaml
  jobs/satellite6-libvirt-install.yaml
  jobs/satellite6-mass-registration.yaml
  jobs/satellite6-upgrader.yaml
Labels: review

#1500 Added support for 6.6 to all jobs
  jobs/builders/satellite6_automation_builders.yaml
  jobs/builders/satellite6_automation_reports_builders.yaml
  jobs/builders/satellite6_consolidated_reports_builders.yaml
  jobs/builders/satellite6_polarion_testcase_run_builders.yaml
  jobs/builders/satellite6_polarion_testrun_builders.yaml
  jobs/builders/satellite6_standalone_automation_builders.yaml
  jobs/builders/satellite6_upgrade_builders.yaml
  jobs/builders/satellite6_upgrade_existence_builders.yaml
  jobs/builders/satellite6_upgrade_scenarios_builders.yaml
  jobs/builders/satellite6_upgrade_tiers_builders.yaml
  jobs/capsule-installer.yaml
  jobs/custom-certs-automation.yaml
  jobs/foreman-maintain-automation.yaml
  jobs/parameters/satellite6_upgrade_parameters.yaml
  jobs/satellite6-client-populate.yaml
  jobs/satellite6-discovery-remaster.yaml
  jobs/satellite6-handle-tier-instances.yaml
  jobs/satellite6-libvirt-install.yaml
  jobs/satellite6-populate.yaml
  jobs/satellite6-rcm-compose.yaml
  jobs/satellite6-upgrader.yaml
  scripts/foreman-maintain-automation.sh
  scripts/satellite6-client-arch-template.sh
  scripts/satellite6-configure.sh
  scripts/satellite6-populate-capsule-template.sh
  scripts/satellite6-populate-template.sh
  scripts/satellite6_db_upgrade_migrate.sh
Labels: review

#1505 Fix SAT_VERSION export
  scripts/satellite6-populate-template.sh
Labels: review

#1512 Environemnt Variables for upgrade scenarios are now robottelo properties
  scripts/satellite6-upgrade-run-scenarios.sh
Labels: review

#1516 add report_portal feed pipeline
  jenkins_jobs.ini.sample
  jobs/satellite6-automation.yaml
  jobs/satellite6-report-portal.yaml
  workflows/qe/satellite6-report-portal.groovy
Labels: CI/CP, pipelines

#1519 Add masked pass for manifest downloader
  jobs/satellite6-manifest-downloader.yaml
Labels: review

#1520 make the satellite6-report-portal run conditionally only on completed builds
  jobs/satellite6-automation.yaml
Labels: CI/CP

#1521 Fix ids of default org and loc
  scripts/satellite6-populate-template.sh
Labels: review
