Repository SatelliteQE/robottelo-ci, pull requests merged in 2020-08, with the labels that each got.

#1814 Update betelgeuse testrun and testplan uploads to set in progress status
  scripts/satellite6-betelgeuse-test-run.sh
Labels: CI/CP

#1820 Use betelgeuse test-run --status arg
  scripts/satellite6-betelgeuse-test-case.sh
  scripts/satellite6-betelgeuse-test-run.sh
Labels: CI-Regression

#1822 Consolidate all polarion test runs in one
  scripts/satellite6-betelgeuse-test-run.sh
Labels: enhancement, review
